#!/bin/sh -e

LOGFILE="/var/log/codid.log" #Chemin du fichier de log
PIDFILE="/var/run/codid_dev.pid" #Chemin pour PID
 
#DAEMON="/opt/appengine/bin/dev_appserver.sh" #ligne de commande du programme
#DAEMONOPT="-p 8888 -a 0.0.0.0 /home/nizarayed/git/appinventor-sources/appinventor/appengine/build/war/ > $LOGFILE 2>&1"  #argument à utiliser par le programme
DAEMON="/opt/codi-studio/codi.sh" #ligne de commande du programme
USER="codi" #utilisateur du programme
NAME="codid_dev" #Nom du programme (doit être identique à l'exécutable).
#Attention le script est un script bash, le script ne portera donc pas l'extension .py mais .sh.
 
PATH="/sbin:/bin:/usr/sbin:/usr/bin" #Ne pas toucher
 
test -x $DAEMON || exit 0
 
. /lib/lsb/init-functions
 
d_start () {
        log_daemon_msg "Starting system $NAME Daemon"
#	start-stop-daemon --background --name $DAEMONNAME --start --quiet --chuid $DAEMONUSER --startas /bin/bash -- -c "exec $DAEMON $DAEMONOPT > $DAEMONLOG 2>&1"
#       start_daemon -p $PIDFILE $DAEMON $DAEMONOPT
	start-stop-daemon --background --pidfile $PIDFILE --name $NAME --start --quiet --chuid root --startas $DAEMON
        log_end_msg $?
}
 
d_stop () {
        log_daemon_msg "Stopping system $daemon_NAME Daemon"
#        start-stop-daemon --stop --retry 5 --quiet --name $DAEMONNAME
        killproc -p $PIDFILE $DAEMON
#	log_end_msg $?
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
}
 
case "$1" in
 
        start|stop)
                d_${1}
                ;;
 
        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;
 
        force-stop)
               d_stop
                killall -q $NAME || true
                sleep 2
                killall -q -9 $NAME || true
                ;;
 
        status)
                status_of_proc "$NAME" "$DAEMON" "system-wide $NAME" && exit 0 || exit $?
                ;;
        *)
                echo "Usage: /etc/init.d/$NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
